_p("menu", "&File");
_p("menu", "&Edit");
_p("menu", "&View");
_p("menu", "&Image Pool");
_p("menu", "&Help");
_p("menu", "Set Target Base Folder...");
_p("menu", "Open Target Base Folder");
_p("menu", "Rename File...");
_p("menu", "Open Containing Folder");
_p("menu", "Exit");
_p("menu", "Undo");
_p("menu", "Copy to Clipboard");
_p("menu", "Settings...");
_p("menu", "Auto Advance");
_p("menu", "Reset Scale Mode Each Pic");
_p("menu", "Enable Auto Repeat");
_p("menu", "Transform");
_p("menu", "Flip X");
_p("menu", "Flip Y");
_p("menu", "Rotate Left");
_p("menu", "Rotate Right");
_p("menu", "Zoom");
_p("menu", "Zoom In");
_p("menu", "Zoom Out");
_p("menu", "Zoom to Width...");
_p("menu", "Zoom to Height...");
_p("menu", "Reset");
_p("menu", "Hide Menubar");
_p("menu", "Fullscreen");
_p("menu", "View KeyFolders table");
_p("menu", "Navigate");
_p("menu", "Next Image");
_p("menu", "Previous Image");
_p("menu", "Go to First");
_p("menu", "Go to Last");
_p("menu", "Forward Jump (Medium)");
_p("menu", "Backward Jump (Medium)");
_p("menu", "Forward Jump (Large)");
_p("menu", "Backward Jump (Large)");
_p("menu", "Moves");
_p("menu", "Left items...");
_p("menu", "Right items...");
_p("menu", "Including current item");
_p("menu", "Add Images...");
_p("menu", "Add from Folder...");
_p("menu", "Clear");
_p("menu", "Learn the Clear hotkeys...");
_p("menu", "Add in Random Order");
_p("menu", "Randomize Order Now");
_p("menu", "Reverse Order Now");
_p("menu", "Go to...");
_p("menu", "View Help");
_p("menu", "View project...");
_p("menu", "About PhotoSift Ex");
